### ISSUE TITLE
XNBHack fail to extract any content file.

### ISSUE THREAD

**Issue by hfgenman0601** [Pathoschild/StardewXnbHack#19]
I updated the latest SDV and SMAPI and XNBHack.
I try to extract xnb files with XNBHack but the console returns error message below.

Running StardewXnbHack 1.0.8+06fdd8161a1ec054535247f0b5cd988360cb6d81.
Found game folder: F:\Steam\steamapps\common\Stardew Valley\.
Loading game instance...
NoFpsCap: This feature is not available

Unhandled exception: Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found.
 ---> System.IO.FileNotFoundException: Could not find file 'F:\Steam\steamapps\common\Stardew Valley\Content\Fonts\tinyFontBorder.xnb'.
File name: 'F:\Steam\steamapps\common\Stardew Valley\Content\Fonts\tinyFontBorder.xnb'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Xna.Framework.TitleContainer.PlatformOpenStream(String safeName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\TitleContainer.Desktop.cs:line 29
   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\TitleContainer.cs:line 48
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 276
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 289
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) inD:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 319
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 255
   at StardewValley.LocalizedContentManager.Load[T](String assetName, LanguageCode language)
   at StardewValley.LocalizedContentManager.Load[T](String assetName)
   at StardewValley.Game1.LoadContent()
   at StardewValley.GameRunner.LoadContent()
   at Microsoft.Xna.Framework.Game.Initialize() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Game.cs:line 788
   at StardewValley.GameRunner.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Game.cs:line 944
   at Microsoft.Xna.Framework.Game.RunOneFrame() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Game.cs:line 428
   at StardewXnbHack.Program.CreateTemporaryGameInstance(PlatformContext platform, String contentPath) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 325
   at StardewXnbHack.Program.Run(GameRunner game, String gamePath, Func`3 getLogger, Boolean showPressAnyKeyToExit) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 142

Press any key to exit.

**Comment by Pathoschild** [comment]
Hi! Does that still happen using the latest StardewXnbHack 1.1.0 instead? If so, does [resetting your game files](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Reset_your_content_files) say any will be redownloaded?
