### ISSUE TITLE
Fails with Stardew 1.6.4, SMAPI 4.0.7

### ISSUE THREAD

**Issue by scriptsforweirdos** [Pathoschild/StardewXnbHack#21]
Fails with Stardew 1.6.4, SMAPI 4.0.7 on Windows 10. Suspect a version got incremented somewhere?

Error Text as follows:

```Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_MinimumGameVersion' in type 'StardewModdingAPI.Toolkit.Serialization.Models.Manifest' from assembly 'SMAPI.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at StardewValley.LocalMultiplayer.GetStaticFieldsAndDefaults() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 121
   at StardewValley.LocalMultiplayer.Initialize() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 92
   at StardewValley.GameRunner..ctor() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 440
   at StardewXnbHack.Program.CreateTemporaryGameInstance(PlatformContext platform, String contentPath) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 320
   at StardewXnbHack.Program.Run(GameRunner game, String gamePath, Func`3 getLogger, Boolean showPressAnyKeyToExit) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 142
System.TypeLoadException: Method 'get_MinimumGameVersion' in type 'StardewModdingAPI.Toolkit.Serialization.Models.Manifest' from assembly 'SMAPI.Toolkit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.```

**Comment by Pathoschild** [comment]
@scriptsforweirdos That was fixed in StardewXnbHack 1.1.0; feel free to reopen if it still happens with that version. Thanks for reporting it!
